### ISSUE TITLE
Lock Overview does not show all locks

### ISSUE THREAD

**Issue by mibo-fdc** [freiheit-com/kuberpult#2132]
A larger set of locks is missing in the lock overview. The locks are verified to be there. The application overview shows the lock still on the applications.

This is blocking, as there is currently no way do delete the locks and to update the applications.

**Comment by ana-caldeira** [comment]
Hello. Any news here? We had a big incident two weeks ago and needed to lock 2 services in multiple prod environments due to that. Now we need to clean up the locks, since the fixes arrived to prod, but have no way of doing it due to this issue.

Im worried this might lead to more problems for us. Do you have some feedback on the issue, or can offer any workaround to remove the locks in another way?

**Comment by AminSlk** [comment]
Hello. This issue is fixed in the new release of kuberpult: https://github.com/freiheit-com/kuberpult/issues/2132
