### ISSUE TITLE
Changing Domainnames

### ISSUE THREAD

**Issue by Murtaza-Solangi** [freiheit-com/kuberpult#964]
Hi, We have a use-case in which we want to migrate kuberpult to a new domain that is only privately accessible. What is the recommended way to approach this problem?
Do we need to start another kuberpult instance parallel? Or is it possible to configure kuberpult to accept multiple domains? For example this variable: "KUBERPULT_ALLOWED_ORIGINS" Can it have multiple values?

**Comment by sven-urbanski-freiheit-com** [comment]
It's fine to have 2 kuberpult instances running on the same repo, as long as they don't get a lot of requests at the same time. By requests I mean any action that writes to the mono repo (locking, deployments...). This is because whenever one instances pushes to the git repo, the other needs to pull. Both push and pull are rather slow operations.

I would suggest:
* Start up new kuberpult instance in new domain.
* Migrate CI/CD to use new domain.
* Stop old kuberpult instance.

Alternatively, I suppose you could edit the kuberpult-ingress manually and add another host there, but that sounds dangerous to me.

`KUBERPULT_ALLOWED_ORIGINS` only supports one value afaik, but you can set it to `*` to allow anything: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by Murtaza-Solangi** [comment]
Thanks a lot for the precise and clear answer.

**Comment by Murtaza-Solangi** [comment]
Can I choose a custom ingressClass for my Kuberpult or Can I only use the default ingressClass?

**Comment by Murtaza-Solangi** [comment]
https://github.com/freiheit-com/kuberpult/pull/974
PR für ingressclass as an optional helm parameter

**Comment by sven-urbanski-freiheit-com** [comment]
Fixed with 1.7.0
